### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by AlexisRoy35** [wearestancer/cms-woocommerce#1]
Hi,

I Can't find the the release on Wordpress. Is it live?
I have the latest version and everything that requested the Readme.
Is there a trick to find and install the plugin?

Many thanks!

**Comment by jdslv** [comment]
Hello,

The module is not available for the moment on the marketplace, it should be soon. I was waiting for some testers returns before publishing it. 

You can find a ready to use package on GitLab https://gitlab.com/wearestancer/cms/woocommerce/-/releases (and some documentation, in French)
